In [6]:
import mxnet as mx
from mxnet import nd
x = nd.arange(12, ctx=mx.cpu());
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [8]:
x.shape

(12,)

In [9]:
x.size

12

In [12]:
x = x.reshape((3,4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [13]:
x = nd.arange(12)
x = x.reshape((-1,4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [14]:
x = nd.arange(12)
x = x.reshape((3,-1))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [16]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [23]:
nd.ones((2,3,4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [19]:
y = nd.array([[1,2], [1,2], [1,2]])
y


[[1. 2.]
 [1. 2.]
 [1. 2.]]
<NDArray 3x2 @cpu(0)>

In [21]:
nd.random.normal(0,1, shape =(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [25]:
x = nd.array([1, 2])
y = nd.ones_like(x) * 2
print('x = ', x)
print('y = ', y)

x =  
[1. 2.]
<NDArray 2 @cpu(0)>
y =  
[2. 2.]
<NDArray 2 @cpu(0)>


In [26]:
print('x + y', x + y)
print('x * y', x * y)
print('x / y', x / y)
print('x - y', x - y)

x + y 
[3. 4.]
<NDArray 2 @cpu(0)>
x * y 
[2. 4.]
<NDArray 2 @cpu(0)>
x / y 
[0.5 1. ]
<NDArray 2 @cpu(0)>
x - y 
[-1.  0.]
<NDArray 2 @cpu(0)>


In [27]:
x.exp()


[2.7182817 7.389056 ]
<NDArray 2 @cpu(0)>

In [34]:
x = nd.arange(12).reshape((3,4))
print(x)
y = nd.array([[1,2, 1, 2],[1,2,1,2],[1,2,1,2]])
print(y)
y.T
nd.dot(x, y.T)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[1. 2. 1. 2.]
 [1. 2. 1. 2.]
 [1. 2. 1. 2.]]
<NDArray 3x4 @cpu(0)>



[[10. 10. 10.]
 [34. 34. 34.]
 [58. 58. 58.]]
<NDArray 3x3 @cpu(0)>

In [35]:
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [36]:
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [39]:
x[1,2] = 9
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [40]:
x[0:2, :] = 12
x


[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [42]:
before = id(y)
print(before)
y = y + x 
id(y) == before
print(id(y))

4753946384
4760650136


In [43]:
z = y.zeros_like()
print('id(z)', id(z))
z[:] = x + y
print('id(z)', id(z))

id(z) 4760650528
id(z) 4760650528


In [44]:
import numpy as py
x = nd.arange(12)
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>


In [46]:
#Scalars
x = nd.array([3.0])
y = nd.array([2.0])
print(x+y)


[5.]
<NDArray 1 @cpu(0)>


In [47]:
x = nd.arange(4)
print(x)


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>


In [48]:
x.shape

(4,)

In [49]:
A = nd.arange(20).reshape((5,4))

In [50]:
print(A)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>


In [52]:
X = nd.arange(24).reshape((2,3,4))
print('X.shape = ', X.shape)
print('X=',X)

X.shape =  (2, 3, 4)
X= 
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


In [60]:
x = nd.arange(12).reshape((3,4))
y = nd.ones(4)
print(x)
print(y)
print(x, y, nd.dot(x,y))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[ 6. 22. 38.]
<NDArray 3 @cpu(0)>


In [62]:
x = nd.arange(12).reshape((3,4))
y = nd.arange(12).reshape((3,4))
print(x)
print(y)
# print(x, y, nd.dot(x,y))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
